// Generated by ACOS. DO NOT EDIT.
// Source: .ssot/agents/mcp.json

import { defineMcpClientConnection } from 'eve/connections';
import { once } from 'eve/tools/approval';

export default defineMcpClientConnection({
  url: "http://localhost:8051/",
  description: "MCP server: archon",
  auth: undefined,
  approval: once(),
  tools: undefined,
});
